version: "3.9"
services:
  frontend:
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile.prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      COOKIE: ${COOKIE}
      SECRET: ${SECRET}
      ID: ${ID}
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

volumes:
  db:
