# Build stage
FROM node:20 AS builder
WORKDIR /app
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
COPY src/package*.json src/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY src .
RUN yarn build

# Serve stage
FROM nginx:stable
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
